services:
  - type: web
    name: eventhub
    env: python
    rootDir: event_management
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn event_management.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventhub_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: USE_CLOUDINARY
        value: "True"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dqf5gwaus"
      - key: CLOUDINARY_API_KEY
        value: "796246568861258"
      - key: CLOUDINARY_API_SECRET
        value: "ACM3VlwOqiVjCKqWJ_y_JhklUHo"
      - key: RESEND_API_KEY
        value: "re_UYDGFWY8_HjdRNg8v7Ftup1DMqrsiWbPf"
      - key: EMAIL_HOST_USER
        value: "resend"
      - key: EMAIL_HOST_PASSWORD
        value: "re_UYDGFWY8_HjdRNg8v7Ftup1DMqrsiWbPf"


databases:
  - name: eventhub_db
    plan: free
