# Generated by Django 6.0.3 on 2026-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent',
            new_name='paystack_authorization_code',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_session_id',
            new_name='paystack_reference',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('paypal', 'PayPal'), ('free', 'Free')], default='paystack', max_length=20),
        ),
    ]
