# Generated by Django 4.2 on 2026-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_instagram_link_customuser_twitter_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
